### ISSUE TITLE
Scopus icon missing?

### ISSUE THREAD

**Issue by nicholas-owen** [diogo-fernan/academicons#12]
I noticed that the Scopus icon from Acadmicons (https://jpswalsh.github.io/academicons/) seems to be missing from the LaTeX package?

**Comment by diogo-fernan** [comment]
Seems so, alongside some others that I missed. In the meantime, I ran into an issue with another icon that seems to be due to the `academicons.ttf` font file. I have opened an issue on the Academicons repository: https://github.com/jpswalsh/academicons/issues/180.

Hopefully, they will look into it soon and a new version of the package will be subsequently published.
