### ISSUE TITLE
arXiv icon

### ISSUE THREAD

**Issue by FMuro** [diogo-fernan/academicons#2]
It's said in the docs that the arXiv icon command is \aiarXiv but it doesn't work for me, while \aiArxiv does work.

**Comment by diogo-fernan** [comment]
Are you sure? Can you provide some background and output?

The definition in the package, as shown below and in https://github.com/diogo-fernan/academicons/blob/master/academicons.sty#L53-L60, defines the command with an uppercase "X", rather than "A" as you state. Note the `\aiarXiv` and `\aiarXivSquare` definitions. The documentation uses these macros.

```
\expandafter\def\csname%
  aiicon@arxiv\endcsname{\symbol{"E808}}
\def\aiarXiv{{\AI\csname%
  aiicon@arxiv\endcsname}}
\expandafter\def\csname%
  aiicon@arxiv-square\endcsname{\symbol{"E809}}
\def\aiarXivSquare{{\AI\csname%
  aiicon@arxiv-square\endcsname}}

```

**Comment by FMuro** [comment]
Sorry, I didn't check here, my fault, I'm using the TeX Live distribution in Fedora, where academicons.sty contains the definition of the commands `\aiArxiv` and  `\aiArxivSquare` and not with a different capitalization. I don't know what the origin of this change may be. BTW thanks for your work in these icons.
